FROM python:3.10-slim

# Install dependency sistem untuk GDAL/Rasterio
RUN apt-get update && apt-get install -y \
    build-essential \
    gdal-bin \
    libgdal-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /code

# Copy file requirements dan install
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# Copy seluruh isi folder project ke dalam container
COPY . /code

# Jalankan Uvicorn di port 7860 (Port default Hugging Face)
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7860"]